// all statuses, ETA config, mock data

import { ClipboardList, Clock, CheckCircle, XCircle, ShoppingBag } from 'lucide-react';

export const STATUS_CONFIG = {
  pending: {
    label: 'Pending',
    color: 'bg-amber-100 text-amber-700 border-amber-300',
    dot: 'bg-amber-500',
    icon: Clock,
    eta: 'Waiting to be confirmed...',
    etaMinutes: null,
    step: 0,
  },
  preparing: {
    label: 'Preparing',
    color: 'bg-blue-100 text-blue-700 border-blue-300',
    dot: 'bg-blue-500',
    icon: ClipboardList,
    eta: 'Ready in ~15 mins',
    etaMinutes: 15,
    step: 1,
  },
  ready: {
    label: 'Ready for Pickup',
    color: 'bg-purple-100 text-purple-700 border-purple-300',
    dot: 'bg-purple-500',
    icon: ShoppingBag,
    eta: 'Ready for pickup now! 🎉',
    etaMinutes: 0,
    step: 2,
  },
  picked_up: {
    label: 'Picked Up',
    color: 'bg-green-100 text-green-700 border-green-300',
    dot: 'bg-green-500',
    icon: CheckCircle,
    eta: 'Completed',
    etaMinutes: null,
    step: 3,
  },
  paid: {
    label: 'Paid',
    color: 'bg-green-100 text-green-700 border-green-300',
    dot: 'bg-green-500',
    icon: CheckCircle,
    eta: 'Payment received',
    etaMinutes: null,
    step: 3,
  },
  cancelled: {
    label: 'Cancelled',
    color: 'bg-red-100 text-red-700 border-red-300',
    dot: 'bg-red-400',
    icon: XCircle,
    eta: 'Order cancelled',
    etaMinutes: null,
    step: -1,
  },
};

export const TRACKING_STEPS = [
  { key: 'pending',   label: 'Order Confirmed', icon: ClipboardList, desc: 'Your order has been received' },
  { key: 'preparing', label: 'Preparing',        icon: Clock,         desc: 'The canteen is preparing your food' },
  { key: 'ready',     label: 'Ready for Pickup', icon: ShoppingBag,   desc: 'Head to the counter to collect your order' },
  { key: 'picked_up', label: 'Picked Up',         icon: CheckCircle,   desc: 'Enjoy your meal!' },
];

export const PICKUP_LOCATIONS = [
  'Main Canteen Counter',
  'Block A Café',
  'Library Café',
  'Block B Canteen',
  'Sports Complex Kiosk',
];

export const TIME_SLOTS = [
  '08:00 AM', '08:30 AM', '09:00 AM', '09:30 AM',
  '10:00 AM', '10:30 AM', '11:00 AM', '11:30 AM',
  '12:00 PM', '12:30 PM', '01:00 PM', '01:30 PM',
  '02:00 PM', '02:30 PM', '03:00 PM', '03:30 PM',
  '04:00 PM', '04:30 PM', '05:00 PM',
];

export const MOCK_ORDERS = [
  // Today's Orders - Pending
  {
    id: 'ORD-2501',
    customer: 'Kasun Perera',
    studentId: 'IT21234567',
    phone: '+94 77 123 4567',
    location: 'Main Canteen Counter',
    items: [
      { name: 'Biryani Rice', category: 'Rice Dishes', qty: 2, price: 420 },
      { name: 'Mango Juice', category: 'Beverages', qty: 1, price: 120 },
    ],
    total: 960,
    status: 'pending',
    time: '02:32 PM',
    scheduledPickup: '3:00 PM',
    notes: 'Less spicy please',
    date: '2026-03-25',
    email: 'kasun@student.edu.lk',
  },
  {
    id: 'ORD-2502',
    customer: 'Nimali Silva',
    studentId: 'IT21345678',
    phone: '+94 71 987 6543',
    location: 'Library Café',
    items: [
      { name: 'Veggie Kottu', category: 'Street Food', qty: 1, price: 420 },
      { name: 'Water Bottle', category: 'Beverages', qty: 2, price: 60 },
    ],
    total: 540,
    status: 'pending',
    time: '02:45 PM',
    scheduledPickup: '3:15 PM',
    notes: '',
    date: '2026-03-25',
    email: 'nimali@student.edu.lk',
  },

  // Today's Orders - Preparing
  {
    id: 'ORD-2503',
    customer: 'Dinesh Fernando',
    studentId: 'IT21456789',
    phone: '+94 76 555 7890',
    location: 'Block A Café',
    items: [
      { name: 'Fish Curry Rice', category: 'Rice Dishes', qty: 1, price: 380 },
      { name: 'Ginger Tea', category: 'Beverages', qty: 1, price: 80 },
    ],
    total: 460,
    status: 'preparing',
    time: '01:55 PM',
    scheduledPickup: '2:30 PM',
    notes: 'More lemon please',
    date: '2026-03-25',
    email: 'dinesh@student.edu.lk',
  },
  {
    id: 'ORD-2504',
    customer: 'Sachini Rathnayake',
    studentId: 'IT21567890',
    phone: '+94 78 222 3344',
    location: 'Sports Complex Kiosk',
    items: [
      { name: 'Chicken Sandwich', category: 'Sandwiches', qty: 2, price: 180 },
      { name: 'Fries', category: 'Sides', qty: 1, price: 120 },
    ],
    total: 480,
    status: 'preparing',
    time: '02:10 PM',
    scheduledPickup: '2:45 PM',
    notes: '',
    date: '2026-03-25',
    email: 'sachini@student.edu.lk',
  },
  {
    id: 'ORD-2505',
    customer: 'Tharindu Bandara',
    studentId: 'IT21678901',
    phone: '+94 70 444 1122',
    location: 'Main Canteen Counter',
    items: [
      { name: 'Noodles Special', category: 'Noodles', qty: 2, price: 290 },
      { name: 'Lime Soda', category: 'Beverages', qty: 2, price: 100 },
    ],
    total: 780,
    status: 'preparing',
    time: '02:58 PM',
    scheduledPickup: '3:30 PM',
    notes: 'Extra sauce on the side',
    date: '2026-03-25',
    email: 'tharindu@student.edu.lk',
  },

  // Today's Orders - Ready
  {
    id: 'ORD-2506',
    customer: 'Amaya Jayasinghe',
    studentId: 'IT21789012',
    phone: '+94 77 888 5566',
    location: 'Block B Canteen',
    items: [
      { name: 'Fried Rice', category: 'Rice Dishes', qty: 1, price: 320 },
      { name: 'Chocolate Milk', category: 'Beverages', qty: 1, price: 140 },
    ],
    total: 460,
    status: 'ready',
    time: '01:05 PM',
    scheduledPickup: '1:30 PM',
    notes: '',
    date: '2026-03-25',
    email: 'amaya@student.edu.lk',
  },
  {
    id: 'ORD-2507',
    customer: 'Ravi Kumar',
    studentId: 'IT21890123',
    phone: '+94 75 999 2233',
    location: 'Main Canteen Counter',
    items: [
      { name: 'Lamprais', category: 'Main Course', qty: 1, price: 450 },
      { name: 'Passion Fruit Juice', category: 'Beverages', qty: 1, price: 150 },
    ],
    total: 600,
    status: 'ready',
    time: '12:30 PM',
    scheduledPickup: '1:00 PM',
    notes: 'Warm it up well',
    date: '2026-03-25',
    email: 'ravi@student.edu.lk',
  },
  {
    id: 'ORD-2508',
    customer: 'Priya Desai',
    studentId: 'IT21901234',
    phone: '+94 76 333 4455',
    location: 'Library Café',
    items: [
      { name: 'Veggie Spring Rolls', category: 'Starters', qty: 2, price: 200 },
      { name: 'Green Tea', category: 'Beverages', qty: 1, price: 80 },
    ],
    total: 480,
    status: 'ready',
    time: '01:45 PM',
    scheduledPickup: '2:15 PM',
    notes: '',
    date: '2026-03-25',
    email: 'priya@student.edu.lk',
  },

  // Yesterday's Orders - Completed
  {
    id: 'ORD-2401',
    customer: 'Kasun Perera',
    studentId: 'IT21234567',
    phone: '+94 77 123 4567',
    location: 'Main Canteen Counter',
    items: [
      { name: 'Chicken Kottu', category: 'Street Food', qty: 1, price: 480 },
      { name: 'Orange Juice', category: 'Beverages', qty: 1, price: 130 },
    ],
    total: 610,
    status: 'picked_up',
    time: '09:15 AM',
    scheduledPickup: '10:00 AM',
    notes: '',
    date: '2026-03-24',
    email: 'kasun@student.edu.lk',
  },
  {
    id: 'ORD-2402',
    customer: 'Nimali Silva',
    studentId: 'IT21345678',
    phone: '+94 71 987 6543',
    location: 'Library Café',
    items: [
      { name: 'Club Sandwich', category: 'Sandwiches', qty: 2, price: 280 },
      { name: 'Iced Tea', category: 'Beverages', qty: 2, price: 100 },
    ],
    total: 660,
    status: 'picked_up',
    time: '08:50 AM',
    scheduledPickup: '09:30 AM',
    notes: '',
    date: '2026-03-24',
    email: 'nimali@student.edu.lk',
  },
  {
    id: 'ORD-2403',
    customer: 'Dinesh Fernando',
    studentId: 'IT21456789',
    phone: '+94 76 555 7890',
    location: 'Block A Café',
    items: [
      { name: 'Chicken Fried Rice', category: 'Rice Dishes', qty: 1, price: 350 },
      { name: 'Pomegranate Juice', category: 'Beverages', qty: 1, price: 160 },
    ],
    total: 510,
    status: 'picked_up',
    time: '10:20 AM',
    scheduledPickup: '11:00 AM',
    notes: 'No mushrooms',
    date: '2026-03-24',
    email: 'dinesh@student.edu.lk',
  },
  {
    id: 'ORD-2404',
    customer: 'Sachini Rathnayake',
    studentId: 'IT21567890',
    phone: '+94 78 222 3344',
    location: 'Sports Complex Kiosk',
    items: [
      { name: 'Deviled Preparation', category: 'Main Course', qty: 1, price: 380 },
      { name: 'Watermelon Juice', category: 'Beverages', qty: 1, price: 140 },
    ],
    total: 520,
    status: 'picked_up',
    time: '11:30 AM',
    scheduledPickup: '12:15 PM',
    notes: '',
    date: '2026-03-24',
    email: 'sachini@student.edu.lk',
  },
  {
    id: 'ORD-2405',
    customer: 'Tharindu Bandara',
    studentId: 'IT21678901',
    phone: '+94 70 444 1122',
    location: 'Main Canteen Counter',
    items: [
      { name: 'Pasta Carbonara', category: 'Pasta', qty: 1, price: 420 },
      { name: 'Mango Smoothie', category: 'Beverages', qty: 1, price: 150 },
    ],
    total: 570,
    status: 'picked_up',
    time: '12:45 PM',
    scheduledPickup: '1:30 PM',
    notes: 'Creamy sauce',
    date: '2026-03-24',
    email: 'tharindu@student.edu.lk',
  },

  // Earlier Orders - Cancelled
  {
    id: 'ORD-2301',
    customer: 'Amaya Jayasinghe',
    studentId: 'IT21789012',
    phone: '+94 77 888 5566',
    location: 'Block B Canteen',
    items: [
      { name: 'Fish and Chips', category: 'Main Course', qty: 1, price: 450 },
      { name: 'Sprite', category: 'Beverages', qty: 1, price: 100 },
    ],
    total: 550,
    status: 'cancelled',
    time: '02:15 PM',
    scheduledPickup: '3:00 PM',
    notes: 'Ordered by mistake',
    date: '2026-03-23',
    email: 'amaya@student.edu.lk',
  },
  {
    id: 'ORD-2302',
    customer: 'Ravi Kumar',
    studentId: 'IT21890123',
    phone: '+94 75 999 2233',
    location: 'Library Café',
    items: [
      { name: 'Dhal Curry', category: 'Curries', qty: 1, price: 280 },
      { name: 'Basmati Rice', category: 'Rice', qty: 1, price: 120 },
    ],
    total: 400,
    status: 'cancelled',
    time: '10:50 AM',
    scheduledPickup: '11:30 AM',
    notes: '',
    date: '2026-03-23',
    email: 'ravi@student.edu.lk',
  },

  // More Recent Completed Orders
  {
    id: 'ORD-2201',
    customer: 'Priya Desai',
    studentId: 'IT21901234',
    phone: '+94 76 333 4455',
    location: 'Main Canteen Counter',
    items: [
      { name: 'Paneer Tikka Masala', category: 'Curries', qty: 1, price: 480 },
      { name: 'Naan Bread', category: 'Bread', qty: 2, price: 100 },
      { name: 'Mango Lassi', category: 'Beverages', qty: 1, price: 160 },
    ],
    total: 740,
    status: 'picked_up',
    time: '12:30 PM',
    scheduledPickup: '1:15 PM',
    notes: 'Mild spice level',
    date: '2026-03-22',
    email: 'priya@student.edu.lk',
  },
  {
    id: 'ORD-2202',
    customer: 'Sanjay Patel',
    studentId: 'IT21012345',
    phone: '+94 77 555 8899',
    location: 'Block A Café',
    items: [
      { name: 'Vegetable Biryani', category: 'Rice Dishes', qty: 1, price: 380 },
      { name: 'Mint Lemonade', category: 'Beverages', qty: 1, price: 120 },
    ],
    total: 500,
    status: 'picked_up',
    time: '11:00 AM',
    scheduledPickup: '11:45 AM',
    notes: '',
    date: '2026-03-22',
    email: 'sanjay@student.edu.lk',
  },

  // Additional Sample Orders with Diverse Names
  {
    id: 'ORD-2509',
    customer: 'Anil Kumar',
    studentId: 'IT21123456',
    phone: '+94 77 234 5678',
    location: 'Block B Canteen',
    items: [
      { name: 'Mutton Kottu', category: 'Street Food', qty: 1, price: 520 },
      { name: 'Ice Lemon Tea', category: 'Beverages', qty: 1, price: 100 },
    ],
    total: 620,
    status: 'pending',
    time: '03:10 PM',
    scheduledPickup: '3:45 PM',
    notes: 'Spicy',
    date: '2026-03-25',
    email: 'anil@student.edu.lk',
  },
  {
    id: 'ORD-2510',
    customer: 'Chandrika Silva',
    studentId: 'IT21234321',
    phone: '+94 76 345 6789',
    location: 'Library Café',
    items: [
      { name: 'Egg Kottu', category: 'Street Food', qty: 1, price: 380 },
      { name: 'Papaya Juice', category: 'Beverages', qty: 1, price: 130 },
    ],
    total: 510,
    status: 'preparing',
    time: '02:20 PM',
    scheduledPickup: '3:00 PM',
    notes: '',
    date: '2026-03-25',
    email: 'chandrika@student.edu.lk',
  },
  {
    id: 'ORD-2511',
    customer: 'Vikram Sharma',
    studentId: 'IT21345123',
    phone: '+94 75 456 7890',
    location: 'Sports Complex Kiosk',
    items: [
      { name: 'Chicken Biryani', category: 'Rice Dishes', qty: 1, price: 450 },
      { name: 'Lassi', category: 'Beverages', qty: 2, price: 120 },
    ],
    total: 690,
    status: 'preparing',
    time: '01:50 PM',
    scheduledPickup: '2:30 PM',
    notes: 'Extra yogurt',
    date: '2026-03-25',
    email: 'vikram@student.edu.lk',
  },
  {
    id: 'ORD-2512',
    customer: 'Deepa Nair',
    studentId: 'IT21456234',
    phone: '+94 77 567 8901',
    location: 'Main Canteen Counter',
    items: [
      { name: 'Chow Mein', category: 'Noodles', qty: 1, price: 320 },
      { name: 'Sprite', category: 'Beverages', qty: 1, price: 100 },
    ],
    total: 420,
    status: 'ready',
    time: '01:30 PM',
    scheduledPickup: '2:00 PM',
    notes: '',
    date: '2026-03-25',
    email: 'deepa@student.edu.lk',
  },
  {
    id: 'ORD-2513',
    customer: 'Mohit Gupta',
    studentId: 'IT21567345',
    phone: '+94 76 678 9012',
    location: 'Block A Café',
    items: [
      { name: 'Hakka Noodles', category: 'Noodles', qty: 1, price: 350 },
      { name: 'Mango Smoothie', category: 'Beverages', qty: 1, price: 140 },
    ],
    total: 490,
    status: 'ready',
    time: '12:15 PM',
    scheduledPickup: '1:00 PM',
    notes: 'No onions please',
    date: '2026-03-25',
    email: 'mohit@student.edu.lk',
  },
  {
    id: 'ORD-2203',
    customer: 'Anjali Reddy',
    studentId: 'IT21678456',
    phone: '+94 75 789 0123',
    location: 'Library Café',
    items: [
      { name: 'Vegetable Fried Rice', category: 'Rice Dishes', qty: 1, price: 340 },
      { name: 'Pineapple Juice', category: 'Beverages', qty: 1, price: 140 },
    ],
    total: 480,
    status: 'picked_up',
    time: '10:30 AM',
    scheduledPickup: '11:15 AM',
    notes: '',
    date: '2026-03-22',
    email: 'anjali@student.edu.lk',
  },
  {
    id: 'ORD-2204',
    customer: 'Naveen Kumar',
    studentId: 'IT21789567',
    phone: '+94 77 890 1234',
    location: 'Block B Canteen',
    items: [
      { name: 'Shrimp Biryani', category: 'Rice Dishes', qty: 1, price: 520 },
      { name: 'Guava Juice', category: 'Beverages', qty: 1, price: 120 },
    ],
    total: 640,
    status: 'picked_up',
    time: '01:00 PM',
    scheduledPickup: '1:45 PM',
    notes: 'Fresh garnish',
    date: '2026-03-22',
    email: 'naveen@student.edu.lk',
  },
  {
    id: 'ORD-2514',
    customer: 'Shreya Bansal',
    studentId: 'IT21890678',
    phone: '+94 76 901 2345',
    location: 'Main Canteen Counter',
    items: [
      { name: 'Onion Dosa', category: 'South Indian', qty: 2, price: 200 },
      { name: 'Sambhar', category: 'Curries', qty: 1, price: 100 },
      { name: 'Filter Coffee', category: 'Beverages', qty: 1, price: 80 },
    ],
    total: 560,
    status: 'pending',
    time: '03:25 PM',
    scheduledPickup: '4:00 PM',
    notes: 'Crispy dosa',
    date: '2026-03-25',
    email: 'shreya@student.edu.lk',
  },
  {
    id: 'ORD-2515',
    customer: 'Rahul Verma',
    studentId: 'IT21901789',
    phone: '+94 75 012 3456',
    location: 'Sports Complex Kiosk',
    items: [
      { name: 'Masala Dosa', category: 'South Indian', qty: 1, price: 250 },
      { name: 'Chutney', category: 'Sides', qty: 1, price: 50 },
    ],
    total: 300,
    status: 'pending',
    time: '03:40 PM',
    scheduledPickup: '4:15 PM',
    notes: '',
    date: '2026-03-25',
    email: 'rahul@student.edu.lk',
  },
  {
    id: 'ORD-2516',
    customer: 'Pooja Mishra',
    studentId: 'IT22012890',
    phone: '+94 77 123 4567',
    location: 'Block A Café',
    items: [
      { name: 'Idli', category: 'South Indian', qty: 4, price: 120 },
      { name: 'Coconut Chutney', category: 'Sides', qty: 1, price: 60 },
      { name: 'Sambar', category: 'Curries', qty: 1, price: 100 },
    ],
    total: 280,
    status: 'preparing',
    time: '03:35 PM',
    scheduledPickup: '4:10 PM',
    notes: '',
    date: '2026-03-25',
    email: 'pooja@student.edu.lk',
  },

  // Additional "Grab & Go" Style Orders
  {
    id: 'ORD-3001',
    customer: 'Priya Sharma',
    studentId: 'IT22123001',
    phone: '+94 77 234 5678',
    location: 'Main Canteen Counter',
    items: [
      { name: 'Rice & Curry Combo', category: 'Combos', qty: 1, price: 500 },
    ],
    total: 500,
    status: 'ready',
    time: '04:00 PM',
    scheduledPickup: '4:30 PM',
    notes: '',
    date: '2026-03-25',
    email: 'priya.sharma@student.edu.lk',
  },
  {
    id: 'ORD-3002',
    customer: 'Raj Patel',
    studentId: 'IT22234002',
    phone: '+94 76 345 6789',
    location: 'Library Café',
    items: [
      { name: 'Rice & Curry Combo', category: 'Combos', qty: 2, price: 500 },
      { name: 'Sprite', category: 'Beverages', qty: 1, price: 60 },
    ],
    total: 1060,
    status: 'pending',
    time: '03:55 PM',
    scheduledPickup: '4:25 PM',
    notes: '',
    date: '2026-03-25',
    email: 'raj.patel@student.edu.lk',
  },
  {
    id: 'ORD-3003',
    customer: 'Arjun Singh',
    studentId: 'IT22345003',
    phone: '+94 75 456 7890',
    location: 'Block A Café',
    items: [
      { name: 'Vegetable Rice & Curry', category: 'Rice Dishes', qty: 1, price: 220 },
      { name: 'Water', category: 'Beverages', qty: 1, price: 60 },
    ],
    total: 280,
    status: 'pending',
    time: '03:50 PM',
    scheduledPickup: '4:20 PM',
    notes: '',
    date: '2026-03-25',
    email: 'arjun.singh@student.edu.lk',
  },
  {
    id: 'ORD-3004',
    customer: 'Sneha Gupta',
    studentId: 'IT22456004',
    phone: '+94 77 567 8901',
    location: 'Sports Complex Kiosk',
    items: [
      { name: 'Vegetable Rice & Curry', category: 'Rice Dishes', qty: 1, price: 220 },
    ],
    total: 220,
    status: 'pending',
    time: '04:05 PM',
    scheduledPickup: '4:35 PM',
    notes: '',
    date: '2026-03-25',
    email: 'sneha.gupta@student.edu.lk',
  },
  {
    id: 'ORD-3005',
    customer: 'Vikrant Joshi',
    studentId: 'IT22567005',
    phone: '+94 76 678 9012',
    location: 'Block B Canteen',
    items: [
      { name: 'Rice & Curry Combo', category: 'Combos', qty: 1, price: 480 },
    ],
    total: 480,
    status: 'pending',
    time: '04:10 PM',
    scheduledPickup: '4:40 PM',
    notes: '',
    date: '2026-03-25',
    email: 'vikrant.joshi@student.edu.lk',
  },
  {
    id: 'ORD-3006',
    customer: 'Meera Iyer',
    studentId: 'IT22678006',
    phone: '+94 75 789 0123',
    location: 'Main Canteen Counter',
    items: [
      { name: 'Rice & Curry Combo', category: 'Combos', qty: 1, price: 500 },
    ],
    total: 500,
    status: 'pending',
    time: '04:15 PM',
    scheduledPickup: '4:45 PM',
    notes: '',
    date: '2026-03-25',
    email: 'meera.iyer@student.edu.lk',
  },
  {
    id: 'ORD-3007',
    customer: 'Karan Malhotra',
    studentId: 'IT22789007',
    phone: '+94 77 890 1234',
    location: 'Library Café',
    items: [
      { name: 'Chicken Fried Rice', category: 'Rice Dishes', qty: 1, price: 320 },
    ],
    total: 320,
    status: 'pending',
    time: '04:20 PM',
    scheduledPickup: '4:50 PM',
    notes: '',
    date: '2026-03-25',
    email: 'karan.malhotra@student.edu.lk',
  },
  {
    id: 'ORD-3008',
    customer: 'Ananya Roy',
    studentId: 'IT22890008',
    phone: '+94 76 901 2345',
    location: 'Block A Café',
    items: [
      { name: 'Vegetable Rice & Curry', category: 'Rice Dishes', qty: 1, price: 280 },
    ],
    total: 280,
    status: 'pending',
    time: '04:25 PM',
    scheduledPickup: '4:55 PM',
    notes: '',
    date: '2026-03-25',
    email: 'ananya.roy@student.edu.lk',
  },
  {
    id: 'ORD-3009',
    customer: 'Nikhil Desai',
    studentId: 'IT22901009',
    phone: '+94 75 012 3456',
    location: 'Sports Complex Kiosk',
    items: [
      { name: 'Rice & Curry Combo', category: 'Combos', qty: 1, price: 280 },
    ],
    total: 280,
    status: 'pending',
    time: '04:30 PM',
    scheduledPickup: '5:00 PM',
    notes: '',
    date: '2026-03-25',
    email: 'nikhil.desai@student.edu.lk',
  },
  {
    id: 'ORD-3010',
    customer: 'Divya Nambiar',
    studentId: 'IT23012010',
    phone: '+94 77 123 4567',
    location: 'Block B Canteen',
    items: [
      { name: 'Rice & Curry Combo', category: 'Combos', qty: 1, price: 280 },
    ],
    total: 280,
    status: 'pending',
    time: '04:35 PM',
    scheduledPickup: '5:05 PM',
    notes: '',
    date: '2026-03-25',
    email: 'divya.nambiar@student.edu.lk',
  },
  {
    id: 'ORD-3011',
    customer: 'Sahil Khan',
    studentId: 'IT23123011',
    phone: '+94 76 234 5678',
    location: 'Main Canteen Counter',
    items: [
      { name: 'Rice & Curry Combo', category: 'Combos', qty: 1, price: 280 },
    ],
    total: 280,
    status: 'pending',
    time: '04:40 PM',
    scheduledPickup: '5:10 PM',
    notes: '',
    date: '2026-03-25',
    email: 'sahil.khan@student.edu.lk',
  },
  {
    id: 'ORD-3012',
    customer: 'Leena Kapoor',
    studentId: 'IT23234012',
    phone: '+94 77 345 6789',
    location: 'Library Café',
    items: [
      { name: 'Schezwan Noodles', category: 'Noodles', qty: 1, price: 340 },
      { name: 'Lemon Iced Tea', category: 'Beverages', qty: 1, price: 90 },
    ],
    total: 430,
    status: 'preparing',
    time: '04:45 PM',
    scheduledPickup: '5:15 PM',
    notes: 'Less oil',
    date: '2026-03-25',
    email: 'leena.kapoor@student.edu.lk',
  },
  {
    id: 'ORD-3013',
    customer: 'Manoj Iyer',
    studentId: 'IT23345013',
    phone: '+94 75 456 7891',
    location: 'Block A Café',
    items: [
      { name: 'Mild Chicken Curry', category: 'Curries', qty: 1, price: 420 },
      { name: 'Parotta', category: 'Bread', qty: 2, price: 80 },
    ],
    total: 580,
    status: 'pending',
    time: '04:50 PM',
    scheduledPickup: '5:30 PM',
    notes: '',
    date: '2026-03-25',
    email: 'manoj.iyer@student.edu.lk',
  },
  {
    id: 'ORD-3014',
    customer: 'Zara Khan',
    studentId: 'IT23456014',
    phone: '+94 76 567 8902',
    location: 'Block B Canteen',
    items: [
      { name: 'Falafel Wrap', category: 'Wraps', qty: 1, price: 320 },
      { name: 'Orange Juice', category: 'Beverages', qty: 1, price: 120 },
    ],
    total: 440,
    status: 'ready',
    time: '04:55 PM',
    scheduledPickup: '5:20 PM',
    notes: 'No garlic',
    date: '2026-03-25',
    email: 'zara.khan@student.edu.lk',
  },
];


